services:
  postgres:
    image: postgres:17.4
    container_name: postgres
    ports:
      - "6543:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: users,products,orders
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./docker/postgres/multiple-databases.sh:/docker-entrypoint-initdb.d/multiple-databases.sh

  user:
    container_name: user
    build:
      context: ./services
      dockerfile: ./Dockerfile
      target: user
      args:
        - NAME=user
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/users
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://user:5000/graphql || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./services/user:/services/user
    ports:
      - 5001:5000
    depends_on:
      postgres:
        condition: service_healthy

  product:
    container_name: product
    build:
      context: ./services
      dockerfile: ./Dockerfile
      target: product
      args:
        - NAME=product
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/products
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://product:5000/graphql || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./services/product:/services/product
    ports:
      - 5002:5000
    depends_on:
      postgres:
        condition: service_healthy

  order:
    container_name: order
    build:
      context: ./services
      dockerfile: ./Dockerfile
      target: order
      args:
        - NAME=order
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/orders
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://order:5000/graphql || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./services/order:/services/order
    ports:
      - 5003:5000
    depends_on:
      postgres:
        condition: service_healthy

  gateway:
    container_name: gateway
    build:
      context: ./gateway
      dockerfile: ./Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      user:
        condition: service_healthy
      product:
        condition: service_healthy
      order:
        condition: service_healthy
