"""empty message

Revision ID: bad8f97cafd3
Revises: 0cdad2b0ac33
Create Date: 2022-04-26 02:01:05.679926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bad8f97cafd3'
down_revision = '0cdad2b0ac33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('created_by', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'created_by')
    # ### end Alembic commands ###
